### ISSUE TITLE
报这个错误

### ISSUE THREAD

**Issue by shaohao2014** [flc1125/alidayu#10]
stdClass Object ( [code] => 29 [msg] => Invalid app Key [sub_code] => isv.appkey-not-exists [request_id] => 157dmzyz5gdag )

**Comment by shaohao2014** [comment]
app key 和 app_secret 都没错

**Comment by flc1125** [comment]
按说明的是提示app key问题，请在检查看下

**Comment by shaohao2014** [comment]
我试了两个app key 和 app_secret 都出错，我再官网上测试就没有问题

**Comment by flc1125** [comment]
可以试图咨询下官方客服！代码没有调整过，使用的用户都没有这个问题！

**Comment by shaohao2014** [comment]
官方咨询过了，我是在thinkphp5环境下使用的

**Comment by flc1125** [comment]
好的，能否提供相关使用代码，appkey，secret注意不要暴露！我明天看下，现在在外地

**Comment by shaohao2014** [comment]
我再入口文件里：require __DIR__ . '/../vendor/alidayu/autoload.php';

**Comment by shaohao2014** [comment]
我直接用的你的DEMO，Client::configure($config);  // 只需定义一次

$rs = Client::request('alibaba.aliqin.fc.sms.num.send', function (IRequest $req) {
    $req->setRecNum('13255478845')
        ->setSmsParam([
            'code' => rand(100000, 999999)
        ])
        ->setSmsFreeSignName('XXX')
        ->setSmsTemplateCode('SMS_66014113');
});

**Comment by shaohao2014** [comment]
找到问题了，沙箱环境设置为false就行了
