### ISSUE TITLE
现在阿里大鱼已经停止新用户加入了,都转到阿里云->短信里了,最重要的是他们的短信发送的API无法共用,请问什么时候能支持阿里短信

### ISSUE THREAD

**Issue by zangsilu** [flc1125/alidayu#12]

**Comment by flc1125** [comment]
我抽时间看下阿里短信，看是否需要开发一个阿里短信接口！静候佳音！

**Comment by zangsilu** [comment]
要的,我现在就碰到这种情况了, 换上了阿里云短信服务的签名与模板,换上了阿里云的access key 发送短信 返回 "scope ids is 11022 11600 11863"

**Comment by zangsilu** [comment]
代码还是原来composer安装的你的代码 阿里大鱼的access key是可以的  阿里云短信的不行   我发现阿里大鱼的access key是一串数字 而阿里云短信的 access key 是一串数字+字母的杂串

**Comment by flc1125** [comment]
阿里短信跟阿里大于本身数据两个业务。虽说同是阿里旗下，但本质还是不一样的！阿里短信的接口，计划会写一个扩展包。过段时间会发布！

**Comment by flc1125** [comment]
扩展包已经开发完成：https://github.com/flc1125/dysms   目前仅做了简单测试，未完全测试！使用谨慎，近期会迭代更新，发布稳定版！

**Comment by guoqicai** [comment]
大哥现在这个阿里云短信验证能用了吗 我又走弯路了研究一天 你发的那个阿里大鱼的就是不用

**Comment by flc1125** [comment]
@guoqicai 很早就发布了稳定版。现在已经可以用了！

**Comment by guoqicai** [comment]
我遇上的跟楼上的错误一样 object(stdClass)#323 (5) { ["code"]=> int(11) ["msg"]=> string(28) "Insufficient isv permissions" ["sub_code"]=> string(32) "isv.permission-api-package-limit" ["sub_msg"]=> string(30) "scope ids is 11022 11600 11863" ["request_id"]=> string(12) "2swll7njz1qc" }

**Comment by flc1125** [comment]
@guoqicai 参考：https://github.com/flc1125/dysms

**Comment by guoqicai** [comment]
谢谢啊 我的哥 我之前那个是不是要删了?

**Comment by flc1125** [comment]
阿里大于与阿里云短信本身就属2个产品（即使都是阿里巴巴旗下）。如果阿里大于对你没什么用，可以删掉！

**Comment by guoqicai** [comment]
$sendSms->setOutId('demo'); 这句是什么意思 别走啊 我先弄下出来问题帮我解决下谢谢新手

**Comment by flc1125** [comment]
`OutId`：官方解释：外部流水扩展字段（非必填项）。你可以不用。一般是用于自身业务拓展

**Comment by guoqicai** [comment]
qq号多少加个好友

**Comment by flc1125** [comment]
![image](https://user-images.githubusercontent.com/14297703/33769762-5298d496-dc66-11e7-9769-07069bef4193.png)

**Comment by guoqicai** [comment]
我下载不下来是怎么回事 composer报错 Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

**Comment by flc1125** [comment]
请先尝试自行解决问题！都是基础问题！

**Comment by guoqicai** [comment]
报这个错怎么回事啊哥 还在吗求解答   stdClass Object ( [Message] => 模板变量缺少对应参数值 [RequestId] => 0F27F582-3E55-4C50-85E7-338501AA7B8E [Code] => isv.TEMPLATE_MISSING_PARAMETERS )

**Comment by guoqicai** [comment]
$config = [
                'accessKeyId'    => 'LTAIIm7XJiTqigSB',
                'accessKeySecret' => 'yBvL4A7FiywZosaEIQZ5AS8F1gKDua',
            ];

            $client  = new Client($config);
            $sendSms = new SendSms;
            $sendSms->setPhoneNumbers('15652981510');
            $sendSms->setSignName('郭先生');
            $sendSms->setTemplateCode('SMS_91150133');
            $sendSms->setTemplateParam(['code' => rand(100000, 999999)]);
            $sendSms->setOutId('demo');

            print_r($client->execute($sendSms));

这是代码按照你的实例写的

**Comment by zangsilu** [comment]
@guoqicai 应该是你短信模板里定义的验证码变量名与你代码里的不一致

**Comment by guoqicai** [comment]
stdClass Object ( [Message] => 签名不合法(不存在或被拉黑) [RequestId] => 414217FB-AD5F-4EE0-8FB3-033BBA15EEA0 [Code] => isv.SMS_SIGNATURE_ILLEGAL )    这是什么意思啊哥

**Comment by guoqicai** [comment]
怎么解决啊哥指教下吧谢谢
