### ISSUE TITLE
请问可否支持阿里云语音服务

### ISSUE THREAD

**Issue by laurelee** [flc1125/alidayu#13]
叶大  现在阿里大于的语音通信功能已经加入阿里云中了  阿里云语音服务的SDK 写的那么不友好  网上检索 短信的方案比较多  文本转语音通知的文档很少    请问可以支持下阿里云的语音服务吗  万分感谢

**Comment by flc1125** [comment]
具体提供下接口文档的地址，看下是说的是哪个接口！

**Comment by laurelee** [comment]
叶大 是这个  文本转语音外呼API(SingleCallByTts) https://help.aliyun.com/document_detail/55447.html  多谢了

**Comment by flc1125** [comment]
你好，确认目前不支持。阿里云的接口，目前只有短信的：https://github.com/flc1125/dysms

**Comment by laurelee** [comment]
叶大  目前这块网上相关的资料也很少 案例也很少  阿里的文档写的不是那么明白  能否烦劳您抽空开发一个语音通信的sdk呢  万分感谢

**Comment by flc1125** [comment]
目前还没有计划去做！感谢使用
