### ISSUE TITLE
您好，有两个问题

### ISSUE THREAD

**Issue by coding1995** [flc1125/alidayu#14]
第一个问题点击注册直接报错
![Uploading image.png…]()

第二个问题，我把上面那个屏蔽之后出现
stdClass Object ( [code] => 11 [msg] => Insufficient isv permissions [sub_code] => isv.permission-api-package-limit [sub_msg] => scope ids is 11022 11600 11863 [request_id] => ut1a52vjjfq )

**Comment by flc1125** [comment]
图片看不了，不清楚什么问题！

**Comment by coding1995** [comment]
你好，第一个问题我已经解决了
还有一个问题
当我点击发送验证码时
返回的是
stdClass Object ( [code] => 11 [msg] => Insufficient isv permissions [sub_code] => isv.permission-api-package-limit [sub_msg] => scope ids is 11022 11600 11863 [request_id] => ut1a52vjjfq )
我弄了很久，都不知道是哪里出了问题

**Comment by flc1125** [comment]
![image](https://user-images.githubusercontent.com/14297703/29368238-b503e4b6-82d1-11e7-9242-efa77736f547.png)


官方给的答复：https://api.alidayu.com/apitools/errorCodeSearch?spm=a3142.7395905.4.30.JBvbI4

----

- api名称：alibaba.aliqin.fc.sms.num.send
- 子错误码：isv.permission-api-package-limit

**Comment by coding1995** [comment]
谢谢
