### ISSUE TITLE
关于阿里2017年12月20日至2018年1月21日短信平台迁移公告

### ISSUE THREAD

**Issue by J-meng7** [flc1125/alidayu#15]
2017年12月20日至2018年1月21日属于消息服务中的短信功能和云市场（阿里短信服务）平台迁移期，您已经进入迁移中状态，请尽快参照《迁移帮助手册》，下载并更换新的SDK及API代码。 请问这个公告有影响吗？ 这公告最重要有句请更换洗呢SDK及API代码

**Comment by flc1125** [comment]
目测应该是统一迁移到阿里短信，参考：https://github.com/flc1125/dysms
