### ISSUE TITLE
如何集成进ThinkPHP 3.2.3?

### ISSUE THREAD

**Issue by goodbuildwhc** [flc1125/alidayu#4]
请问怎么集成进去呢？能给具体步骤吗？我按说明集成提示，Class 'Flc\Alidayu\Client' not found

**Comment by flc1125** [comment]
1. 在项目根目录使用`composer require flc/alidayu`安装阿里大鱼包。
2. 然后在入口文件`index.php`，写入`require __DIR__ . '/vendor/autoload.php'`；**必须写在引入TP官方(`ThinkPHP.php`)之前**
