### ISSUE TITLE
linux下报method不存在 应该是路径有问题

### ISSUE THREAD

**Issue by Dummercn** [flc1125/alidayu#5]
linux下报method不存在 应该是路径有问题

**Comment by flc1125** [comment]
在具体操作什么的情况下，提示这个？使用composer安装的时候？

**Comment by Dummercn** [comment]
不是的  在thinkphp 上使用的 我当做拓展引入的实惠 在win下面可以正常使用 在Linux下面时候提示找不到当前命名空间的这个类

**Comment by flc1125** [comment]
你看下你win和linux的php版本是多少。如果php5.3以前不支持命名空间！当前这个插件要求php必须5.4以上。而且在win和linux都有使用过。均正常。

**Comment by dzymail** [comment]
我也遇到类不存在的问题,路径我检查了仍然不行。
require_once  alidayu/autoload.php;

use Flc\Alidayu\Client;
use Flc\Alidayu\App;
use Flc\Alidayu\Requests\AlibabaAliqinFcSmsNumSend;
use Flc\Alidayu\Requests\IRequest;

用教程示例的方法一运行到这里时
$req = new AlibabaAliqinFcSmsNumSend;
Error: Class 'Flc\Alidayu\Requests\AlibabaAliqinFcSmsNumSend' not found 

用方法二运行时提示
Exception: method不存在 in Flc\Alidayu\Client::request() (line 242 of alidayu/src/Alidayu/Client.php）

我用的是 php 7.0.4, MacOS 10

**Comment by flc1125** [comment]
问题已接收，我尽快检查下

**Comment by flc1125** [comment]
已修复！
