### ISSUE TITLE
Laravel下报错，Flc\Alidayu\Client类找不到

### ISSUE THREAD

**Issue by sml2h3** [flc1125/alidayu#7]
FatalThrowableError in Controller.php line 68:
Class 'Flc\Alidayu\Client' not found

**Comment by sml2h3** [comment]
FatalThrowableError in Controller.php line 68:
Class 'Flc\Alidayu\Client' not found
Laravel 5.4版本

**Comment by sml2h3** [comment]
忘了说了环境，Centos 7,php7.0

**Comment by flc1125** [comment]
你是什麼方式引入的？

**Comment by sml2h3** [comment]
直接compose,composer require flc/alidayu
然后
use Flc\Alidayu\Client;
use Flc\Alidayu\App;
use Flc\Alidayu\Requests\AlibabaAliqinFcSmsNumSend;
use Flc\Alidayu\Requests\IRequest;

**Comment by flc1125** [comment]
那我可以说不会吗？我试过很多次均正常。而且众多网友也有用过，而且不限于laravel。都没有此问题！

**Comment by sml2h3** [comment]
我在我自己mac上也没问题，一到服务器里面就报错了。。我具体的环境PHP 7.0.7，centos 6.8，php探针http://123.57.138.167/p.php

**Comment by flc1125** [comment]
你是通过什么方式将代码传到服务器上的？是不是git？如果是，那需要考虑相关文件是不是对应传上去了。git本身忽略了一部分文件，包括根目录的vendor目录

**Comment by sml2h3** [comment]
直接ftp的呢，我在ssh里面看了一下flc的文件夹里面东西也不缺啊

**Comment by flc1125** [comment]
建议你把整个vendor文件夹重新上传。如果你只是传了flc那个文件夹，对应的autoload的一些文件没有上传，就会出现你这个问题！

**Comment by sml2h3** [comment]
好的，我试试看看

**Comment by flc1125** [comment]
`vendor\composer`主要是这个文件夹！

**Comment by sml2h3** [comment]
果然，上传了这个就ok了

**Comment by flc1125** [comment]
建议去了解下`composer`自动载入文件的原理:smile:
