### ISSUE TITLE
些许建议

### ISSUE THREAD

**Issue by BrownHu** [flc1125/alidayu#8]
参考了文档和代码发现api仅适合已充值账户使用，在Flc\Alidayu\Requests\AlibabaAliqinFcSmsNumSend::setSmsTemplateCode处必须传参数，方便尝鲜使用可以略加修改，本地测试成功。

**Comment by flc1125** [comment]
:sweat_smile: 感謝建議，不過我可以說我沒看明白你的意思嗎？可以在說明白點！:smile::smile:

**Comment by BrownHu** [comment]
新申请的用户没有自定义模版的权限，自然在传templatecode时就没办法继续了，那smssend部分的测试就down了

**Comment by flc1125** [comment]
:cold_sweat:這塊必須按着官方API來走吧。官方api為必填項。且每個帳戶申請模板ID的都不一致，所以模板ID也沒辦法共享出來使用！除非有提供測試的帳號出來使用，目前官方沒提供。個人提供如果測試量大，那費用也不小！:grin:所以這塊就只能自己去申請使用了

> 官方一般對新用戶會有優惠活動，基本也算是免費使用了！

**Comment by BrownHu** [comment]
OK
