### ISSUE TITLE
有没有验证码功能？

### ISSUE THREAD

**Issue by shaohao2014** [flc1125/alidayu#9]
有没有验证码功能？

**Comment by flc1125** [comment]
有的，可以访问：https://github.com/flc1125/alidayu/blob/master/docs/alibaba_aliqin_fc_sms_num_send.md

**Comment by shaohao2014** [comment]
恩，那个只是发送验证码到客户手机，怎么验证对错呢？
我的问题是，在服务器端需要验证客户输入的验证码对不对，正确的验证码才可以登录我的系统。

**Comment by shaohao2014** [comment]
另外你的功能在大鱼上测试通过了没有？

**Comment by flc1125** [comment]
了解了，你要的是实现校验验证码功能。事实上这个需求与当前插件是两个各自独立的功能点。插件只是实现api对接。具体业务需要自己实现。

----

插件已经有很phper在用了，目前稳定正常！

**Comment by shaohao2014** [comment]
好的，明白了，我以为可以直接用上呢！辛苦了

**Comment by flc1125** [comment]
:thumbsup:
